site_name: {{ cookiecutter.project_name }}
nav:
  - Home: README.md
  - Contributing: contributing.md
theme:
  name: 'material'
repo_url: {{ cookiecutter.github_url }}
remote_branch: gh-pages
remote_name: origin
